### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by valentyna-lytovchenko** [valentyna-lytovchenko/homepage#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by valit2001** [comment]
Джек Лондон про себе: "I believe in the need for systematic work and never wait for inspiration. By nature, I am not only a person, but also a melancholic. But I managed to overcome both in myself. I was greatly influenced by the discipline I learned when I was a sailor."

**Comment by valentyna-lytovchenko** [comment]
Дякую! Що б я без себе робила :)
