### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by valentyna-lytovchenko** [valentyna-lytovchenko/homepage#5]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by valit2001** [comment]
https://www.facebook.com/JackLondonAuthor/
JackLondonWriter@gmail.com
